# Generated by Django 3.2.3 on 2021-07-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=99)),
                ('autor', models.CharField(max_length=99)),
                ('sinopsis', models.TextField()),
                ('precio', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('publicacion', models.DateField()),
            ],
        ),
    ]
