# Generated by Django 3.2.3 on 2021-06-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='productos',
            field=models.ManyToManyField(to='api.Producto'),
        ),
    ]
